# Generated by Django 5.1.6 on 2025-02-18 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('is_auc', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('domestic', models.BooleanField(default=True)),
                ('score', models.IntegerField()),
                ('domain', models.CharField(choices=[('BA', 'Batsman'), ('BO', 'Bowler'), ('AR', 'All Rounder'), ('WK', 'Wicket Keeper')], max_length=2)),
                ('base_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('curr_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.player')),
            ],
        ),
    ]
