# Generated by Django 5.1.6 on 2025-02-11 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='curr_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin.player'),
        ),
    ]
