# Generated by Django 5.1.6 on 2025-02-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_room_curr_player'),
        ('auctioneer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioneer',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin.room'),
        ),
    ]
